title: "Reverb Robotics Documentation"
description: "Documentation for the ReroCore auditory awareness platform and the Rero ROS2 integration."
theme: just-the-docs

# If publishing from /docs on GitHub Pages:
# baseurl: "/<your-repo-name>"
# url: "https://<your-username>.github.io"

url: https://docs.reverbrobotics.ca
baseurl: ""

search_enabled: true

aux_links:
  "Rero Core (source) on GitHub":
    - "https://github.com/reverbrobotics/rero_core"
  "Rero ROS on GitHub":
    - "https://github.com/reverbrobotics/rero_ros"

# Just the Docs options
nav_enabled: true

# Where docs live
collections:
  docs:
    output: true
    permalink: /:collection/:path/
